### ISSUE TITLE
Starting yields errors

### ISSUE THREAD

**Issue by danbachar** [Eusebius1920/fakturama-docker#1]
Hey there,

I know this repository might not be maintained, as the last commit was from two years ago.

My team would like to use Fakturama as a docker container, and I'm trying to get this repository to run. I would love to create a PR when done to fix it.

Currently, when running this on OSX, the following errors pop up and the container crashes: 
`Unable to init server: Could not connect: Connection refused`,
`Fakturama: Cannot open display:`
`JVM terminated. Exit code=130`

`docker -v` output: 
`Docker version 19.03.5, build 633a0ea`

This might be connected to $DISPLAY not being set properly, thus I'd love to know what did you have set when running this.

Would love your input on this!

**Comment by Eusebius1920** [comment]
It is not maintained in the sense that I am activley using it to run Fakturama.

I have no MacOS-Instance at hand, but I was successful with running docker containers in MacOS that used X11 in the past.

* Do you have XQuartz installed? (via Homebrew: `brew cask install xquartz`)
* and configured?

I will try to get my hands on an MacOS machine to give it a try there.

**Comment by Eusebius1920** [comment]
**Addendum**: I should upgrade it to the last Fakturama version first

**Comment by danbachar** [comment]
I didn't have xquartz installed, installing now. 
Is there any xquartz configuration you could share?

Thanks!

**Comment by danbachar** [comment]
> Addendum: I should upgrade it to the last Fakturama version first

I can help, as we're just setting up Fakturama on our machines and would love to get the latest version up and running. Thing is, it fails to run on my mac with JDK 1.8.0_241 so I went ahead with your docker container. Moreover, we ran into problem  when trying to connect it to Woocommerce (through the neos connector). 

It's amazing to hear that you have it already running though 😄

**Comment by Eusebius1920** [comment]
I have updated the image to version 2.0.5 of Fakturama.

If I recall correctly, after you installed XQuartz, you have to 
* Start XQuartz, for example with `open -a XQuartz`
* _"allow network connections"_ in preferences of XQuartz,
* you have to find you ip on your network interface, denoted in the following as **IP**. For example: `echo $(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')`
* execute `xhost +local:root` and `xhost +IP` in your MacOS-Terminal (where IP is you result from the previous step)
* you should then be able to run the container via something like (substituting IP and LOCAL_PATH_ON_YOUR_MACHINE):
  ```
  docker run -it --rm \
       --name Fakturama \
       --net=host \
       -e DISPLAY=IP:0 \
       -v /tmp/.X11-unix \
       -v ~/.fakturama2:/root/.fakturama2 \
       -v LOCAL_PATH_ON_YOUR_MACHINE:/root/fakturama-workingdir \
       helloagain/fakturama
  ```

Don't forget to update your image to the newly built latest or use the 2.0.5-tag

If it does not work, feel free to come back with your error-log, I will try to help. But as I mentioned, unfortunately I have no MacOS-Machine at hand currently, where I could try to run the container myself.

**Comment by danbachar** [comment]
awesome, thank you very much! will keep in touch later on this weekend 👍

**Comment by danbachar** [comment]
so, starting with 
```
docker run -it --rm \
     --name Fakturama \
     --net=host \
     -e DISPLAY=<my ip address>:0 \
     -v /tmp/.X11-unix \
     -v ~/.fakturama2:/root/.fakturama2 \
     -v /Users/danbachar/fakturama:/root/fakturama-workingdir \
     helloagain/fakturama:2.0.5
```

or 
```
docker run -it --rm \
     --name Fakturama \
     --net=host \
     -e DISPLAY=IP:0 \
     -v /tmp/.X11-unix \
     -v ~/.fakturama2:/root/.fakturama2 \
     -v /Users/danbachar/fakturama:/root/fakturama-workingdir \
     helloagain/fakturama:2.0.5
```

yields the same error:
```
Unable to init server: Could not connect: Connection refused
Fakturama: Cannot open display:
```

Any clue what I might've done wrong? I ran XQuartz as you've suggested.

**Comment by d-schloss-mvg** [comment]
* Did you replace "IP" with the IP found in the third step?
* Did you allow network connections in XQuartz settings?

**Comment by Eusebius1920** [comment]
* Did you replace "IP" with the IP found in the third step?
* Did you allow network connections in XQuartz settings?

**Comment by danbachar** [comment]
yes and yes

**Comment by danbachar** [comment]
![image](https://user-images.githubusercontent.com/17069732/75773505-569a3380-5d4e-11ea-9144-35e5f60a72ef.png)

also, attaching Fakturama error logs from the container:
```
eclipse.buildId=2.0.5.
java.version=1.8.0_242
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2020-03-03 12:01:40.511
!MESSAGE Anwendungsfehler
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4725)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1040)
	at org.eclipse.swt.widgets.Display.create(Display.java:1020)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:175)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:586)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:577)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:2464)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.getApplicationDisplay(E4Application.java:135)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
```

**Comment by Eusebius1920** [comment]
Can you run other "X11-containers" with your configuration?

Examples:
* docker run -e DISPLAY=IP:0 gns3/xeyes
* docker run -e DISPLAY=IP:0 --privileged jess/chrome
* docker run -e DISPLAY=IP:0 jess/firefox

Did the xhost commands succeed?

**Comment by danbachar** [comment]
* `docker run -e DISPLAY=192.168.178.20:0 gns3/xeyes`
`Error: Can't open display: 192.168.178.20:0`

* `docker run -e DISPLAY=192.168.178.20:0 --privileged jess/chrome`
`[1:1:0303/214445.457711:ERROR:browser_main_loop.cc(1512)] Unable to open X display.`

* `docker run -e DISPLAY=192.168.178.20:0 jess/firefox`
```
(firefox:1): Gtk-WARNING **: 21:44:39.579: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to init server: Broadway display type not supported: 192.168.178.20:0
Error: cannot open display: 192.168.178.20:0
```

**Comment by danbachar** [comment]
I got it! it works when I run it from the XQuartz terminal. Thank you very much for your support!
